spring:
 thymeleaf:
  cache: false
server:
  port: 8443
  ssl:
    key-store: file:///path/to/mykey.jks
    key-store-password: letmein
    key-password: letmein
logging:
  level:
    root: WARN
    org:
      springframework:
        security: debug

